trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: AWSCLI@1
  inputs:
    awsCredentials: 'ado-terraform-session'  # Name of your service connection
    regionName: 'us-west-2'
    command: 'sts get-caller-identity'
