trigger:
  branches:
    include: [ main ]

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: tf-lab-secrets

steps:
- bash: |
    set -e
    # Install Terraform
    curl -fsSL https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip -o tf.zip
    unzip -o tf.zip && sudo mv terraform /usr/local/bin/
    # Install Terragrunt
    TG_VERSION=0.57.0
    curl -fsSL https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64 -o terragrunt
    chmod +x terragrunt && sudo mv terragrunt /usr/local/bin/
  displayName: Install Terraform & Terragrunt

- bash: |
    set -e
    export AZURE_STORAGE_ACCOUNT_NAME="$(AZURE_STORAGE_ACCOUNT_NAME)"
    export AZURE_STORAGE_ACCOUNT_KEY="$(AZURE_STORAGE_ACCOUNT_KEY)"
    export AWS_ACCESS_KEY_ID="$(AWS_ACCESS_KEY_ID)"
    export AWS_SECRET_ACCESS_KEY="$(AWS_SECRET_ACCESS_KEY)"
    cd live/nonprod/us-west-2/s3-demo
    terragrunt init -reconfigure
    terragrunt plan -out tgplan
  displayName: Terragrunt Plan
